# Generated by Django 3.2.20 on 2023-08-05 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='messaged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 19, 45, 104343)),
        ),
    ]
