# Generated by Django 3.2.20 on 2023-08-05 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20230805_1754'),
        ('group_messages', '0002_auto_20230805_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='messaged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 50, 4, 169154)),
        ),
    ]
