# Generated by Django 3.2.20 on 2023-08-05 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_messages', '0003_auto_20230805_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messaged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 54, 27, 806512)),
        ),
    ]
