# Generated by Django 3.2.20 on 2023-08-04 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_messages', '0001_initial'),
        ('group', '0002_alter_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_messages.message'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 13, 26, 39, 292524)),
        ),
    ]
