# Generated by Django 3.2.20 on 2023-08-05 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20230804_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 19, 45, 104935)),
        ),
    ]
