# Generated by Django 3.2.20 on 2023-08-05 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 18, 6, 4, 596737)),
        ),
    ]
